version: '3.5'

services:
  matchanalyzer:
    build: .
    container_name: "matchanalyzer"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "9009:9000"
    networks:
      - ma_backend
networks:
  ma_backend:
