version: '3.5'

services:
  adminmongo:
    image: adicom/admin-mongo
    container_name: adminmongo
    restart: "always"
    stdin_open: true
    tty: true
    environment:
      CONN_NAME: matchanalyzer
      DB_HOST: mongo
      DB_PORT: 27017
    ports:
      - "1234:1234"
    networks:
      - ma_backend
  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    restart: "always"
    stdin_open: true
    tty: true
    environment:
      CONN_NAME: matchanalyzer
      DB_HOST: mongo
      DB_PORT: 27017
    ports:
      - "3330:3000"
    networks:
      - ma_backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080
  matchanalyzer:
    build: .
    container_name: "matchanalyzer"
    restart: always
    stdin_open: true
    tty: true
    environment:
      MONGODB_URI: mongodb://mongo:27017/matchAnalyzer
    ports:
      - "9990:9000"
    networks:
      - ma_backend
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./.data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ma_backend
networks:
  ma_backend:
