name: Primer workflow

on:
  push:
    branches:
      - master

jobs:
  paso1:
    runs-on: ubuntu-latest
    steps:
      - name: Traer el codigo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Instalar dependencias
        run: npm install
        
